// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecryptAsymmetric(arg1, arg2, arg3) {
  return window['go']['main']['App']['DecryptAsymmetric'](arg1, arg2, arg3);
}

export function DecryptSymmetric(arg1, arg2) {
  return window['go']['main']['App']['DecryptSymmetric'](arg1, arg2);
}

export function EncryptAsymmetric(arg1, arg2, arg3) {
  return window['go']['main']['App']['EncryptAsymmetric'](arg1, arg2, arg3);
}

export function EncryptSymmetric(arg1, arg2) {
  return window['go']['main']['App']['EncryptSymmetric'](arg1, arg2);
}

export function ExportPrivateKey(arg1) {
  return window['go']['main']['App']['ExportPrivateKey'](arg1);
}

export function GenerateKeyPair() {
  return window['go']['main']['App']['GenerateKeyPair']();
}

export function GenerateRandomPassword() {
  return window['go']['main']['App']['GenerateRandomPassword']();
}

export function GenerateShareLink(arg1, arg2) {
  return window['go']['main']['App']['GenerateShareLink'](arg1, arg2);
}

export function GenerateShareQRCode(arg1, arg2) {
  return window['go']['main']['App']['GenerateShareQRCode'](arg1, arg2);
}

export function ImportPrivateKey() {
  return window['go']['main']['App']['ImportPrivateKey']();
}

export function OpenRepository() {
  return window['go']['main']['App']['OpenRepository']();
}

export function ShowFilePickerDialog() {
  return window['go']['main']['App']['ShowFilePickerDialog']();
}
