// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecryptAsymmetric(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function DecryptSymmetric(arg1:string,arg2:string):Promise<boolean>;

export function EncryptAsymmetric(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function EncryptSymmetric(arg1:string,arg2:string):Promise<boolean>;

export function ExportPrivateKey(arg1:string):Promise<boolean>;

export function GenerateKeyPair():Promise<Array<string>>;

export function GenerateRandomPassword():Promise<string>;

export function GenerateShareLink(arg1:boolean,arg2:string):Promise<string>;

export function GenerateShareQRCode(arg1:boolean,arg2:string):Promise<string>;

export function ImportPrivateKey():Promise<string>;

export function OpenRepository():Promise<void>;

export function ShowFilePickerDialog():Promise<string>;
